export enum AchievementRuleHandler {
  // Game - Cyball
  CYBALL_CLAIMED_REWARD_TIMES = 'CYBALL_CLAIMED_REWARD_TIMES',
  CYBALL_GAVE_OUT_NFT_TO_RENT = 'CYBALL_GAVE_OUT_NFT_TO_RENT',
  CYBALL_MADE_A_MENTORING = 'CYBALL_MADE_A_MENTORING',
  // Game - Star Shark
  STAR_SHARK_UPGRADE_YOUR_SHARK = 'STAR_SHARK_UPGRADE_YOUR_SHARK',
  STAR_SHARK_MINT_NFT = 'STAR_SHARK_MINT_NFT',
  // Game - Metavers Miners
  METAVERS_MINERS_MINT_NFT = 'METAVERS_MINERS_MINT_NFT',
  METAVERS_MINERS_RECHARGE_ENERGY_TIMES = 'METAVERS_MINERS_RECHARGE_ENERGY_TIMES',
  // Game - X World Games
  X_WORLD_GAMES_MINT_NFT = 'X_WORLD_GAMES_MINT_NFT',
  X_WORLD_GAMES_LEVEL_PRIZE = 'X_WORLD_GAMES_LEVEL_PRIZE',
  // Game - Era7
  ERA7_SUMMONED_PLAYING_CARD = 'ERA7_SUMMONED_PLAYING_CARD',
  ERA7_SIGNED_IN_AT_LEAST_TIMES = 'ERA7_SIGNED_IN_AT_LEAST_TIMES',
  ERA7_BOUGHT_AN_NFT_HERO = 'ERA7_BOUGHT_AN_NFT_HERO',
  // Game - My Rich Farm
  MY_RICH_FARM_LAND_OWNER = 'MY_RICH_FARM_LAND_OWNER',
  MY_RICH_FARM_AVATAR_OWNER = 'MY_RICH_FARM_AVATAR_OWNER',
  MY_RICH_FARM_FUN_ZONE_GAMER_TIMES = 'MY_RICH_FARM_FUN_ZONE_GAMER_TIMES',
  // Game - Meta Keeper
  META_KEEPER_OWNER_OF_ONE_KEEPER_NFT = 'META_KEEPER_OWNER_OF_ONE_KEEPER_NFT',
  META_KEEPER_KEEPERS_LEVEL_UP = 'META_KEEPER_KEEPERS_LEVEL_UP',
  // Game - Faraland
  FARA_LAND_SUMMONED_DEMI_KNIGHT = 'FARA_LAND_SUMMONED_DEMI_KNIGHT',
  FARA_LAND_MOON_KNIGHT_HERO_OWNER = 'FARA_LAND_MOON_KNIGHT_HERO_OWNER',
  FARA_LAND_GACHA_EXPLORER = 'FARA_LAND_GACHA_EXPLORER',
  // Game - Metamon
  META_MON_OPEN_BINANCE_NFT_MYSTERY_BOX_RACA = 'META_MON_OPEN_BINANCE_NFT_MYSTERY_BOX_RACA',
  // Game - The Crypto You
  THE_CRYPTO_YOU_MINTED_BITCOIN_HOLDER_NFT = 'THE_CRYPTO_YOU_MINTED_BITCOIN_HOLDER_NFT',
  // Game - Heroes and Empires
  HEROES_AND_EMPIRES_MINTED_HEA_NFT = 'HEROES_AND_EMPIRES_MINTED_HEA_NFT',
  HEROES_AND_EMPIRES_UPGRADED_BREAK_LIMIT_FOR_HERO = 'HEROES_AND_EMPIRES_UPGRADED_BREAK_LIMIT_FOR_HERO',
  // Game - Binary X
  BINARY_X_OWNS_CYBER_DRAGON_ITEMS_TIMES = 'BINARY_X_OWNS_CYBER_DRAGON_ITEMS_TIMES',
  // Game - Crypto Legions Bloodstone
  CRYPTO_LEGIONS_BLOODSTONE_HUNTS_TIMES = 'CRYPTO_LEGIONS_BLOODSTONE_HUNTS_TIMES',
  // Game - Thetan Arena
  THETAN_ARENA_BOUGHT_THETAN_N_TIMES = 'THETAN_ARENA_BOUGHT_THETAN_N_TIMES',
  THETAN_ARENA_RENTED_ONE_NFT = 'THETAN_ARENA_RENTED_ONE_NFT',
  THETAN_ARENA_FUZED_NFT = 'THETAN_ARENA_FUZED_NFT',
  // Game - Tiny World
  TINY_WORLD_BURN_NFT_TIMES = 'TINY_WORLD_BURN_NFT_TIMES',
  TINY_WORLD_NFT_STAKING_MASTER = 'TINY_WORLD_NFT_STAKING_MASTER',
  TINY_WORLD_NFT_CHECKED_TIMES = 'TINY_WORLD_NFT_CHECKED_TIMES',
  // Game - Metarun
  METARUN_TICKET_SWAP = 'METARUN_TICKET_SWAP',
  METARUN_MYSTERY_BOX_REVEAL = 'METARUN_MYSTERY_BOX_REVEAL',
  // Game - Walken
  SOLANA_WALKEN_BREEDER = 'SOLANA_WALKEN_BREEDER',
  SOLANA_WALKEN_NFT_COLLECTOR = 'SOLANA_WALKEN_NFT_COLLECTOR',
  SOLANA_WALKEN_GAMER = 'SOLANA_WALKEN_GAMER',
  // Shared base handlers
  EARN_USD = 'EARN_USD',
  EARN_CBT = 'EARN_CBT',
  EARN_META = 'EARN_META',
  EARN_MRUN = 'EARN_MRUN',
  SPEND_USD = 'SPEND_USD',
  SOLANA_EARN_USD = 'SOLANA_EARN_USD',
  SOLANA_EARN_WLKN = 'SOLANA_EARN_WLKN',
  SOLANA_SPEND_USD = 'SOLANA_SPEND_USD',
  BREAKEVEN = 'BREAKEVEN',
  GAME_INTERACTION = 'GAME_INTERACTION',
  UNKNOWN = 'UNKNOWN',
}
