export enum ProgressStage {
  STAGE_1 = 'STAGE_1_PRE_COLLECT_TRANSACTIONS',
  STAGE_2_1 = 'STAGE_2_1_PARSING_GAME_TRANSACTIONS',
  STAGE_2_2 = 'STAGE_2_2_PARSING_GAME_TRANSACTIONS_INT_TRX',
  STAGE_3 = 'STAGE_3_PARSING_NFT_LOGS',
  STAGE_4 = 'STAGE_4_PARSING_WALLET_LOGS',
  STAGE_5 = 'STAGE_5_POST_TOKEN_PROCESSING',
  STAGE_6 = 'STAGE_6_POST_LOGS_CREATED_SET',
  STAGE_7 = 'STAGE_7_POST_FIRST_TIME_SET',
  STAGE_8 = 'STAGE_8_USER_TRANSACTION_AGGREGATION',
  STAGE_9 = 'STAGE_9_COLLECT_UNKNOWN_TOKEN_PRICES',
}
